### GET 1
GET http://localhost:8080/api?a=1


### GET 2
GET http://localhost:8080/api?a=2


### GET 3
GET http://localhost:8080/api?a=3


### GET 4
GET http://localhost:8080/api?a=4


### POST
POST http://localhost:8080/api?a=2
Content-Type: application/json; charset=utf-8

{
  "param0": "value0",
  "param1": "value1"
}


### PUT
PUT http://localhost:8080/api?s=2
Content-Type: application/json; charset=utf-8

{
  "param0": "value0",
  "param1": "value1"
}


### Bun GET
GET http://localhost:8080/test?queryKey=sadasdasd&q=1


### Bun POST
POST http://localhost:8080/test?queryKey=sadasdasd&q=1
Content-Type: application/json; charset=utf-8

{
  "param0": "value0",
  "param1": "value1"
}
