name: Release

on: workflow_dispatch

jobs:
  release: 
    runs-on: ubuntu-latest
    permissions:
      contents: write # For git operations
      id-token: write # < REQUIRED FOR OIDC
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install latest npm
        run: npm install -g npm@latest
      - name: Install the dependencies
        run: npm ci
      - name: Initialize Git user
        run: |
            git config --global user.email "volatilization@yandex.ru" 
            git config --global user.name "volatilization"
      - name: Run release
        run: npm run release:no-increment
        env:
          RELEASE_IT_GITHUB_TOKEN: ${{ secrets.RELEASE_IT_GITHUB_TOKEN  }}
          COVERAGE_MIN_PERCENT: ${{ vars.COVERAGE_MIN_PERCENT }}
