name: Test hook

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.4
      - run: npm run test:coverage
        env:
          COVERAGE_MIN_PERCENT: ${{vars.coverage_min_percent}}
      - run: bun run test:bun:coverage
        env:
          COVERAGE_MIN_PERCENT: ${{vars.coverage_min_percent}}